@startuml DataTransmissionLayer
left to right direction

rectangle "Data Transmission Layer" as dataTransmissionLayer {
  rectangle MFL
  rectangle "Omang, Births and Deaths Register" as Omang
  rectangle PIMS {
    rectangle "FHIR Translation Layer" as translationLayer
  }

  rectangle OpenHIM {
    usecase "HL7 v2.4 -- FHIR translation" as OHIM1
    usecase "Shared Health Record" as OHIM2
    rectangle "OpenHIM Mediator" as Mediator
    Mediator ..> OHIM1 : "<<use>>"
    Mediator --> OHIM2 : "Update Records"
  }
  
  rectangle IPMS

  MFL --> Mediator
  Omang --> Mediator

  translationLayer --> Mediator : "PIMS Pushes Orders"
  Mediator --> translationLayer : "PIMS Pulls Results"

  IPMS --> Mediator : "Pushes Lab Results"
  Mediator --> IPMS : "Pushes Lab Orders"
}

@enduml