@startuml RetrievalOfLabOrders
left to right direction
rectangle "OpenHIE - Retrieval Of Lab Orders" as RetrievalOfLabOrders {
  actor "[[ActorDefinition-LaboratoryTechnicianActorDefinitionExample.html Lab Tech]]" as labTech
  rectangle "[[ActorDefinition-IPMSActorDefinitionExample.html IPMS]]" as IPMS {
  usecase "Login" as RLO1
  usecase "Authenticate User" as RLO2
  usecase "Lab Order module" as RLO3
  usecase "Update Lab Order Results" as RLO4
  usecase "Create New Lab Orders" as RLO5
  }

labTech --> RLO1

(RLO1) ..> (RLO2) : "<<use>>"
(RLO3) ..> (RLO4) : "<<use>>"

RLO1 --> RLO3
RLO5 --> RLO3 : "Extends"

  rectangle "[[ActorDefinition-InteroperabilityLayerActorDefinitionExample.html Interoperability Layer]]" as InteroperabilityLayer {
  usecase "Update records" as IL1
  usecase "[[ActorDefinition-SHRActorDefinitionExample.html Shared Health Record]]" as IL2
  usecase "Mediator" as IL3
  usecase "Translate FHIR messages to HL7 v2.4" as IL4
  usecase "[[ActorDefinition-ClientRegistryActorDefinitionExample.html OpenCR]]" as IL5
  }

  IL3 --> RLO3 : "Pushes HL7 v2.4 messages"
  RLO5 --> IL3 : "Create New Client"
  RLO5 --> IL3 : "Create a new lab order"
  IL5 --> IL3 : "Sends patient data"
  IL2 --> IL3 : "Pull Lab Orders"

  (IL2) ..> (IL1) : "<<use>>"
  (IL3) ..> (IL4) : "<<use>>"

  rectangle "[[ActorDefinition-OmangActorDefinitionExample.html Omang]]" as Omang
  rectangle "[[ActorDefinition-BDRSActorDefinitionExample.html Births and Deaths Register]]" as BDRS
  rectangle "[[ActorDefinition-MFLActorDefinitionExample.html Master Facility List]]" as MFL

  (Omang) --> (IL5) : "Update Patients details"
  (BDRS) --> (IL5) : "Update Patients details"
  (MFL) --> (IL5) : "Update Facility details"
}

@enduml