@startuml RetrieveLabResults

rectangle "OpenHIE - Retrieve Lab Results" as RetrieveLabResults {
  actor "Clinician" as clinician
    rectangle PIMS {
  usecase "Login" as RLR1
  usecase "Authenticate User" as RLR2
  usecase "Retrieve Lab Results" as RLR3
  usecase "Enter Lab order ID" as RLR4
  usecase "Data standards translation (FHIR)" as RLR5
  }

clinician --> RLR1

(RLR1) ..> (RLR2) : "<<use>>"
(RLR3) ..> (RLR4) : "<<use>>"

RLR1 --> RLR3
RLR5 --> RLR3 : "Query available lab results"

  rectangle "Interoperability Layer" as IL {
  usecase "Update DB records" as IL1
  usecase "Shared Health Record" as IL2
  }

  IL2 --> RLR5

  (IL2) ..> (IL1) : "<<use>>"
}

@enduml