Instance: ClinicianRequirements
InstanceOf: Requirements
Usage: #example
Title: "Clinician Requirements"
Description: "Clinician Functional Requirements"
* status = #active
* statement[+]
  * key = "BOTS.FR-CR.001"
  * requirement = """As a Clinician, I want to be able to log in to system and access the laboratory module."""
* statement[+]
  * key = "BOTS.FR-CR.002"
  * requirement = """As a Clinician, I want to be able to open the lab order form in the lab module."""
* statement[+]
  * key = "BOTS.FR-CR.003"
  * requirement = """As a Clinician, I want to be able to capture patient details at the facility using the system."""
* statement[+]
  * key = "BOTS.FR-CR.004"
  * requirement = """As a Clinician, I want to be able to capture lab order details at the facility using the system."""
* statement[+]
  * key = "BOTS.FR-CR.005"
  * requirement = """As a Clinician, I want to be able to submit lab order details to the SHR."""
* statement[+]
  * key = "BOTS.FR-CR.006"
  * requirement = """As a Clinician, I want to be able to access the lab test results from PIMS."""
* statement[+]
  * key = "BOTS.FR-CR.007"
  * requirement = """As a Clinician, I want to be able to receive pop up notification from PIMS indicating that new - results have been received."""

Instance: LaboratoryTechnicianRequirements
InstanceOf: Requirements
Usage: #example
Title: "Laboratory Technician Requirements"
Description: "Laboratory Technician Functional Requirements"
* status = #active
* statement[+]
  * key = "BOTS.FR-LTR.001"
  * requirement = """As a Laboratory Technician, I want to be able to log in to access the lab module in IPMS."""
* statement[+]
  * key = "BOTS.FR-LTR.002"
  * requirement = """As a Laboratory Technician, I want to be able to enter lab order details in to IPMS from facilities that do not have IPMS."""
* statement[+]
  * key = "BOTS.FR-LTR.003"
  * requirement = """As a Laboratory Technician, I want to be able to obtain lab order ID generated by IPMS."""
* statement[+]
  * key = "BOTS.FR-LTR.004"
  * requirement = """As a Laboratory Technician, I want to be able to enter results in to IPMS after processing the received specimen."""
* statement[+]
  * key = "BOTS.FR-LTR.005"
  * requirement = """As a Laboratory Technician, I want to be able to submit the lab test results to the SHR through IPMS."""

Instance: InteroperabilityLayerRequirements
InstanceOf: Requirements
Usage: #example
Title: "Interoperability Layer Requirements"
Description: "Interoperability Layer Functional Requirements"
* status = #active
* statement[+]
  * key = "BOTS.FR-ILR.001"
  * requirement = """The interoperability layer should be able to cache and store data from various interfacing systems in the shared health record (SHR)."""
* statement[+]
  * key = "BOTS.FR-ILR.002"
  * requirement = """The interoperability layer should be able to synchronise and update data set in the interoperability layer with other systems such as the MPI."""
* statement[+]
  * key = "BOTS.FR-ILR.003"
  * requirement = """The interoperability layer should be able to ping IPMS for available lab test results and pull them to the SHR."""
* statement[+]
  * key = "BOTS.FR-ILR.004"
  * requirement = """The interoperability layer should be able to update SHR with results from IPMS and push the updated record to PIMS."""

Instance: HIESystemRequirements
InstanceOf: Requirements
Usage: #example
Title: "HIE System Requirements"
Description: "HIE System Functional Requirements"
* status = #active
* statement[+]
  * key = "BOTS.FR-HIE.001"
  * requirement = """The system should be able to send SMS notifications to patients that require urgent attention-(PIMS)."""
* statement[+]
  * key = "BOTS.FR-HIE.002"
  * requirement = """The system should be able to allow capturing of certain specific specimen-(PIMS)."""
* statement[+]
  * key = "BOTS.FR-HIE.003"
  * requirement = """The system should be able to ping SHR for available lab test results and avail them to the clinicians- (PIMS)."""
* statement[+]
  * key = "BOTS.FR-HIE.004"
  * requirement = """The system should be able to send lab test results to the SHR-(IPMS)."""
* statement[+]
  * key = "BOTS.FR-HIE.005"
  * requirement = """The system shall include an interface into which a workflow engine can be connected."""
* statement[+]
  * key = "BOTS.FR-HIE.006"
  * requirement = """The system should support the ability to be extended by allowing additional mediation functions to be added or removed as they are needed."""
* statement[+]
  * key = "BOTS.FR-HIE.007"
  * requirement = """The system shall support a mechanism for error management and tracking, e.g. a console for viewing failed transactions."""
* statement[+]
  * key = "BOTS.FR-HIE.008"
  * requirement = """The system shall allow for failed transactions to be grouped by error type and reason so that errors can be rectified efficiently by finding the root cause of the error, fixing the problem, and re-running those transactions."""
* statement[+]
  * key = "BOTS.FR-HIE.009"
  * requirement = """The system should support the ability for a user to re-run errored transactions through the HIE once the reason for their failure has been rectified."""
* statement[+]
  * key = "BOTS.FR-HIE.010"
  * requirement = """The system shall provide authorized users with a view of metrics for monitoring the flow of messages through the HIE."""
* statement[+]
  * key = "BOTS.FR-HIE.011"
  * requirement = """The system shall manage the security of the HIE through authentication (identity verification), authorization (permission to interact with specified HIE components) and encryption and decryption of messages."""
* statement[+]
  * key = "BOTS.FR-HIE.012"
  * requirement = """The system shall support Authentication and Authorization of systems trying to send data to the HIE."""
* statement[+]
  * key = "BOTS.FR-HIE.013"
  * requirement = """The system should support the encryption of data in flight (when not on a physically secure network) and at rest (whenever data is stored, e.g. when transactions are stored for logging)."""
* statement[+]
  * key = "BOTS.FR-HIE.014"
  * requirement = """The system should capture monitoring statistics, such as transaction loads and performance metrics, and provide a view of these for monitoring the flow of messages through the HIE."""

Instance: NonFunctionalRequirements
InstanceOf: Requirements
Usage: #example
Title: "Non Functional Requirements"
Description: "Non Functional Requirements"
* status = #active
* statement[+]
  * key = "BOTS.NFR.001"
  * requirement = """The system should be able to be recovered 1 hour from downtime."""
* statement[+]
  * key = "BOTS.NFR.002"
  * requirement = """The data should be shared/transmitted over a secure layer (Interoperability Layer)."""
* statement[+]
  * key = "BOTS.NFR.003"
  * requirement = """The system should be scalable."""
* statement[+]
  * key = "BOTS.NFR.004"
  * requirement = """For performance - On average the system should have a cumulative down time of 1 hour per month."""
* statement[+]
  * key = "BOTS.NFR.005"
  * requirement = """For performance - The system should have 99.9% uptime."""
* statement[+]
  * key = "BOTS.NFR.006"
  * requirement = """For performance - System should have a quick response time to end user queries."""
* statement[+]
  * key = "BOTS.NFR.007"
  * requirement = """For security - The system shall detect and log all users, authorized or not, who access (create, read, update or delete) in accordance to the Botswana Data Protection Act 2018."""
* statement[+]
  * key = "BOTS.NFR.008"
  * requirement = """For browser compatibility - The components  of the HIE shall be compatible with Google Chrome version  and  FireFox  version and later."""
* statement[+]
  * key = "BOTS.NFR.009"
  * requirement = """For browser compatibility - If a public user is attempting to access the system without a compatible browser, the system shall display a message to the user that identifies the compatibility requirements necessary to access the system."""
* statement[+]
  * key = "BOTS.NFR.010"
  * requirement = """For maintainability - The software shall exhibit high maintainability to facilitate efficient and timely modifications, updates, and enhancements, ensuring that changes can be made with minimal impact on existing functionality."""