Instance: ClinicianRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Clinician Requirements"
Description: "Clinician Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "ClinicianRequirements"
* status = #active
* actor = Canonical(ClinicianActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-C.001"
  * requirement = "I want to be able to log in to system and access the laboratory module."
* statement[+]
  * key = "BOTS.FR-C.002"
  * requirement = "I want to be able to open the lab order form in the lab module."
* statement[+]
  * key = "BOTS.FR-C.003"
  * requirement = "I want to be able to capture patient details at the facility using the system."
* statement[+]
  * key = "BOTS.FR-C.004"
  * requirement = "I want to be able to capture lab order details at the facility using the system."
* statement[+]
  * key = "BOTS.FR-C.005"
  * requirement = "I want to be able to submit lab order details to the SHR."
* statement[+]
  * key = "BOTS.FR-C.006"
  * requirement = "I want to be able to access the lab test results from PIMS."
* statement[+]
  * key = "BOTS.FR-C.007"
  * requirement = "I want to be able to receive pop up notification from PIMS indicating that new - results have been received."

Instance: LaboratoryTechnicianRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Laboratory Technician Requirements"
Description: "Laboratory Technician Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "LaboratoryTechnicianRequirements"
* status = #active
* actor = Canonical(LaboratoryTechnicianActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-LT.001"
  * requirement = "I want to be able to log in to access the lab module in IPMS."
* statement[+]
  * key = "BOTS.FR-LT.002"
  * requirement = "I want to be able to enter lab order details in to IPMS from facilities that do not have IPMS."
* statement[+]
  * key = "BOTS.FR-LT.003"
  * requirement = "I want to be able to obtain lab order ID generated by IPMS."
* statement[+]
  * key = "BOTS.FR-LT.004"
  * requirement = "I want to be able to enter results in to IPMS after processing the received specimen."
* statement[+]
  * key = "BOTS.FR-LT.005"
  * requirement = "I want to be able to submit the lab test results to the SHR through IPMS."

Instance: InteroperabilityLayerRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Interoperability Layer Requirements"
Description: "Interoperability Layer Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "InteroperabilityLayerRequirements"
* status = #active
* actor = Canonical(InteroperabilityLayerActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-IL.001"
  * requirement = "Should be able to cache and store data from various interfacing systems in the shared health record (SHR)."
* statement[+]
  * key = "BOTS.FR-IL.002"
  * requirement = "Should be able to synchronise and update data set in the interoperability layer with other systems such as the MPI."
* statement[+]
  * key = "BOTS.FR-IL.003"
  * requirement = "Should be able to ping IPMS for available lab test results and pull them to the SHR."
* statement[+]
  * key = "BOTS.FR-IL.004"
  * requirement = "Should be able to update SHR with results from IPMS and push the updated record to PIMS."

Instance: HIESystemRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "HIE System Requirements"
Description: "HIE System Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "HIESystemRequirements"
* status = #active
* actor = Canonical(HIESystemActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-HIE.001"
  * requirement = "Should be able to send SMS notifications to patients that require urgent attention-(PIMS)."
* statement[+]
  * key = "BOTS.FR-HIE.002"
  * requirement = "Should be able to allow capturing of certain specific specimen-(PIMS)."
* statement[+]
  * key = "BOTS.FR-HIE.003"
  * requirement = "Should be able to ping SHR for available lab test results and avail them to the clinicians- (PIMS)."
* statement[+]
  * key = "BOTS.FR-HIE.004"
  * requirement = "Should be able to send lab test results to the SHR-(IPMS)."
* statement[+]
  * key = "BOTS.FR-HIE.005"
  * requirement = "Shall include an interface into which a workflow engine can be connected."
* statement[+]
  * key = "BOTS.FR-HIE.006"
  * requirement = "Should support the ability to be extended by allowing additional mediation functions to be added or removed as they are needed."
* statement[+]
  * key = "BOTS.FR-HIE.007"
  * requirement = "Shall support a mechanism for error management and tracking, e.g. a console for viewing failed transactions."
* statement[+]
  * key = "BOTS.FR-HIE.008"
  * requirement = "Shall allow for failed transactions to be grouped by error type and reason so that errors can be rectified efficiently by finding the root cause of the error, fixing the problem, and re-running those transactions."
* statement[+]
  * key = "BOTS.FR-HIE.009"
  * requirement = "Should support the ability for a user to re-run errored transactions through the HIE once the reason for their failure has been rectified."
* statement[+]
  * key = "BOTS.FR-HIE.010"
  * requirement = "Shall provide authorized users with a view of metrics for monitoring the flow of messages through the HIE."
* statement[+]
  * key = "BOTS.FR-HIE.011"
  * requirement = "Shall manage the security of the HIE through authentication (identity verification), authorization (permission to interact with specified HIE components) and encryption and decryption of messages."
* statement[+]
  * key = "BOTS.FR-HIE.012"
  * requirement = "Shall support Authentication and Authorization of systems trying to send data to the HIE."
* statement[+]
  * key = "BOTS.FR-HIE.013"
  * requirement = "Should support the encryption of data in flight (when not on a physically secure network) and at rest (whenever data is stored, e.g. when transactions are stored for logging)."
* statement[+]
  * key = "BOTS.FR-HIE.014"
  * requirement = "Should capture monitoring statistics, such as transaction loads and performance metrics, and provide a view of these for monitoring the flow of messages through the HIE."

Instance: NonFunctionalRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Non Functional Requirements"
Description: "Non Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#non-functional
* name = "NonFunctionalRequirements"
* status = #active
* statement[+]
  * key = "BOTS.NFR.001"
  * requirement = "The system should be able to be recovered 1 hour from downtime."
* statement[+]
  * key = "BOTS.NFR.002"
  * requirement = "The data should be shared/transmitted over a secure layer (Interoperability Layer)."
* statement[+]
  * key = "BOTS.NFR.003"
  * requirement = "The system should be scalable."
* statement[+]
  * key = "BOTS.NFR.004"
  * requirement = "For performance - On average the system should have a cumulative down time of 1 hour per month."
* statement[+]
  * key = "BOTS.NFR.005"
  * requirement = "For performance - The system should have 99.9% uptime."
* statement[+]
  * key = "BOTS.NFR.006"
  * requirement = "For performance - System should have a quick response time to end user queries."
* statement[+]
  * key = "BOTS.NFR.007"
  * requirement = "For security - The system shall detect and log all users, authorized or not, who access (create, read, update or delete) in accordance to the Botswana Data Protection Act 2018."
* statement[+]
  * key = "BOTS.NFR.008"
  * requirement = "For browser compatibility - The components  of the HIE shall be compatible with Google Chrome version  and  FireFox  version and later."
* statement[+]
  * key = "BOTS.NFR.009"
  * requirement = "For browser compatibility - If a public user is attempting to access the system without a compatible browser, the system shall display a message to the user that identifies the compatibility requirements necessary to access the system."
* statement[+]
  * key = "BOTS.NFR.010"
  * requirement = "For maintainability - The software shall exhibit high maintainability to facilitate efficient and timely modifications, updates, and enhancements, ensuring that changes can be made with minimal impact on existing functionality." 

Instance: ClientRegistryRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Client Registry Requirements"
Description: "Client Registry Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "ClientRegistryRequirements"
* status = #active
* actor = Canonical(ClientRegistryActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-CR.001"
  * requirement = "Should be able to support configurable entity matching, a service to assist in identifying duplicate patients."
* statement[+]
  * key = "BOTS.FR-CR.002"
  * requirement = "Should be able to support patient linking and de-duplication."
* statement[+]
  * key = "BOTS.FR-CR.003"
  * requirement = "Should be able to support the ability to track and monitor inbound/outbound transactions."
* statement[+]
  * key = "BOTS.FR-CR.004"
  * requirement = "Should be able to support synchronization of client IDs with a Shared Health Record (SHR)."
* statement[+]
  * key = "BOTS.FR-CR.005"
  * requirement = "Should be able to manage a full audit log of changes to data as well as configurations as well as users."
* statement[+]
  * key = "BOTS.FR-CR.006"
  * requirement = "Should have functions including user management and access controls."
* statement[+]
  * key = "BOTS.FR-CR.007"
  * requirement = "Should be able to persist the parent/child relationship, birth order, and multi-birth indicator."
* statement[+]
  * key = "BOTS.FR-CR.008"
  * requirement = "Should support a UI to review and manually adjudicate uncertain (“potential”) matches, and override incorrect matches."
* statement[+]
  * key = "BOTS.FR-CR.009"
  * requirement = "Should support configurable attributes that form a patient record and are used for matching."
* statement[+]
  * key = "BOTS.FR-CR.010"
  * requirement = "Should support configurable attributes to make it easy to add attributes to the schema."
* statement[+]
  * key = "BOTS.FR-CR.011"
  * requirement = "Should support configurable attributes to make it easy to remove attributes from the default model (or start over from scratch)."

Instance: OmangRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Omang Requirements"
Description: "Omang Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "OmangRequirements"
* status = #active
* actor = Canonical(OmangActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-OMANG.001"
  * requirement = "Should be able to provide a status check that indicates uptime and connection status."
* statement[+]
  * key = "BOTS.FR-OMANG.002"
  * requirement = "Should be able to authenticate with and connect to the appropriate Oracle View with Omang registry data."
* statement[+]
  * key = "BOTS.FR-OMANG.003"
  * requirement = "Should be able to translate the Omang registry data model into valid FHIR resources."
* statement[+]
  * key = "BOTS.FR-OMANG.004"
  * requirement = "Should be able to provide a FHIR Search API layer for handling queries for Omang patients by all identifiers and demographic parameters available in the Omang Oracle View."
* statement[+]
  * key = "BOTS.FR-OMANG.005"
  * requirement = "Should be able to integrate with an HIE interoperability layer for incoming and outgoing communication."
* statement[+]
  * key = "BOTS.FR-OMANG.006"
  * requirement = "Should be able to connect with a FHIR-based Client Registry through the HIE."
* statement[+]
  * key = "BOTS.FR-OMANG.007"
  * requirement = "Should be able to synchronize patient data on demand between the Omang registry and a FHIR-based HIE Client Registry, with a configurable refresh timespan."

Instance: BirthDeathRegistrationRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Birth and Death Registration System Requirements"
Description: "Birth and Death Registration System Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "BirthDeathRegistrationRequirements"
* status = #active
* actor = Canonical(BDRSActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-BDRS.001"
  * requirement = "Should be able to provide a status check that indicates uptime and connection status."
* statement[+]
  * key = "BOTS.FR-BDRS.002"
  * requirement = "Should be able to authenticate with and connect to the appropriate Oracle View with BDRS registry data."
* statement[+]
  * key = "BOTS.FR-BDRS.003"
  * requirement = "Should be able to translate the BDRS registry data model into valid FHIR resources."
* statement[+]
  * key = "BOTS.FR-BDRS.004"
  * requirement = "Should be able to provide a FHIR Search API layer for handling queries for Omang patients by all identifiers and demographic parameters available in the BDRS Oracle View."
* statement[+]
  * key = "BOTS.FR-BDRS.005"
  * requirement = "Should be able to integrate with an HIE interoperability layer for incoming and outgoing communication."
* statement[+]
  * key = "BOTS.FR-BDRS.006"
  * requirement = "Should be able to connect with a FHIR-based Client Registry through the HIE."
* statement[+]
  * key = "BOTS.FR-BDRS.007"
  * requirement = "Should be able to synchronize patient data on demand between the BDRS registry and a FHIR-based HIE Client Registry, with a configurable refresh timespan."

Instance: ImmigrationCitizenshipSystemRequirements
InstanceOf: BwRequirements
Usage: #example
Title: "Immigration and Citizenship System Requirements"
Description: "Immigration and Citizenship System Functional Requirements"
* extension[RequirementsType].valueCodeableConcept = $RequirementsTypeCodeSystem#functional
* name = "ImmigrationCitizenshipRequirements"
* status = #active
* actor = Canonical(ICSActorDefinitionExample)
* statement[+]
  * key = "BOTS.FR-ICS.001"
  * requirement = "Should be able to provide a status check that indicates uptime and connection status."
* statement[+]
  * key = "BOTS.FR-ICS.002"
  * requirement = "Should be able to authenticate with and connect to the appropriate Oracle View with ICS registry data."
* statement[+]
  * key = "BOTS.FR-ICS.003"
  * requirement = "Should be able to translate the ICS registry data model into valid FHIR resources."
* statement[+]
  * key = "BOTS.FR-ICS.004"
  * requirement = "Should be able to provide a FHIR Search API layer for handling queries for Omang patients by all identifiers and demographic parameters available in the ICS Oracle View."
* statement[+]
  * key = "BOTS.FR-ICS.005"
  * requirement = "Should be able to integrate with an HIE interoperability layer for incoming and outgoing communication."
* statement[+]
  * key = "BOTS.FR-ICS.006"
  * requirement = "Should be able to connect with a FHIR-based Client Registry through the HIE."
* statement[+]
  * key = "BOTS.FR-ICS.007"
  * requirement = "Should be able to synchronize patient data on demand between the ICS registry and a FHIR-based HIE Client Registry, with a configurable refresh timespan."